services:
  examgen:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - DOCKERIZED="true"
    container_name: examgen-app
    extra_hosts:
      - "host.docker.internal:host-gateway"